/*
CASE 6: Passenger Trends
Goal: Fetch the number of flights, days, months and routes of each passenger
*/

SELECT T.PASSENGER_ID,
	MAX(T.PASSENGER_NAME) AS PASSENGER_NAME,
	COUNT(TF.FLIGHT_ID) AS TOTAL_FLIGHTS,
	SUM(TF.AMOUNT) AS TOTAL_SPEND,
	STRING_AGG(DISTINCT TF.FARE_CONDITIONS, ', ') AS FARE_CLASSES,	
	STRING_AGG(DISTINCT CONCAT(F.DEPARTURE_AIRPORT, ' -> ', F.ARRIVAL_AIRPORT), ', ') AS ROUTE,
	STRING_AGG(DISTINCT TRIM(TO_CHAR(F.SCHEDULED_DEPARTURE, 'Month')), ', ') AS MONTH_NAME,
	STRING_AGG(DISTINCT TRIM(TO_CHAR(F.SCHEDULED_DEPARTURE, 'Day')), ', ') AS DAY_NAME
FROM TICKETS T
JOIN TICKET_FLIGHTS TF ON T.TICKET_NO = TF.TICKET_NO
JOIN FLIGHTS F ON TF.FLIGHT_ID = F.FLIGHT_ID
GROUP BY T.PASSENGER_ID
ORDER BY TOTAL_FLIGHTS DESC;
