/*
CASE 2: Flight Counts by Airport
Calculate the count of flights at each airport for each day of the week within a year.
*/

WITH UNION_FLIGHTS AS
	(SELECT FLIGHT_ID,
			DEPARTURE_AIRPORT AS AIRPORT_CODE,
			ACTUAL_DEPARTURE AS DATE_OF_FLIGHT_IN_AIRPORT
		FROM FLIGHTS
		WHERE ACTUAL_DEPARTURE IS NOT NULL
		UNION SELECT FLIGHT_ID,
			ARRIVAL_AIRPORT AS AIRPORT_CODE,
			ACTUAL_ARRIVAL AS DATE_OF_FLIGHT_IN_AIRPORT
		FROM FLIGHTS
		WHERE ACTUAL_ARRIVAL IS NOT NULL )
SELECT AD.AIRPORT_NAME - >> 'en' AS AIRPORT_NAME,
	TO_CHAR(UF.DATE_OF_FLIGHT_IN_AIRPORT,'Day') AS DAY_NAME,
	COUNT(*) AS COUNT_FLIGHTS
FROM UNION_FLIGHTS UF
JOIN AIRPORTS_DATA AD ON UF.AIRPORT_CODE = AD.AIRPORT_CODE
WHERE UF.DATE_OF_FLIGHT_IN_AIRPORT <
		(SELECT MIN(DATE_OF_FLIGHT_IN_AIRPORT)
			FROM UNION_FLIGHTS) + INTERVAL '1 year'
GROUP BY AD.AIRPORT_NAME,
	TO_CHAR(UF.DATE_OF_FLIGHT_IN_AIRPORT, 'Day')
ORDER BY AD.AIRPORT_NAME,
CASE TRIM(TO_CHAR(UF.DATE_OF_FLIGHT_IN_AIRPORT, 'Day'))
	WHEN 'Monday' THEN 1
	WHEN 'Tuesday' THEN 2
	WHEN 'Wednesday' THEN 3
	WHEN 'Thursday' THEN 4
	WHEN 'Friday' THEN 5
	WHEN 'Saturday' THEN 6
	ELSE 7
END;