/*
CASE 7: Analyze Seating Arrangement
Goal: Analyze seat occupancy percentages by type (aisle, window, middle).
*/

WITH FLIGHT_SEATING_SUMMARY AS
	(SELECT F.FLIGHT_ID,
			F.AIRCRAFT_CODE,
			SUM(CASE WHEN SAV.SEATING_ARRANGEMENT = 'aisle seat' THEN 1 ELSE 0 END) AS NUMBER_OCCUPIED_AISLE_SEAT,
			SUM(CASE WHEN SAV.SEATING_ARRANGEMENT = 'window seat' THEN 1 ELSE 0 END) AS NUMBER_OCCUPIED_WINDOW_SEAT,
			SUM(CASE WHEN SAV.SEATING_ARRANGEMENT = 'middle seat' THEN 1 ELSE 0 END) AS NUMBER_OCCUPIED_MIDDLE_SEAT,
			COUNT(*) AS NUMBER_OCCUPIED_SEAT
		FROM FLIGHTS F
		JOIN BOARDING_PASSES BP ON F.FLIGHT_ID = BP.FLIGHT_ID
		JOIN SEATING_ARRANGEMENT_VIEW SAV ON F.AIRCRAFT_CODE = SAV.AIRCRAFT_CODE
		AND BP.SEAT_NO = SAV.SEAT_NO
		GROUP BY F.FLIGHT_ID,
			F.AIRCRAFT_CODE),
	SEAT_SUMMARY AS
	(SELECT AIRCRAFT_CODE,
			SUM(CASE WHEN SEATING_ARRANGEMENT = 'window seat' THEN 1 ELSE 0 END) AS TOTAL_WINDOW_SEAT,
			SUM(CASE WHEN SEATING_ARRANGEMENT = 'middle seat' THEN 1 ELSE 0 END) AS TOTAL_MIDDLE_SEAT,
			SUM(CASE WHEN SEATING_ARRANGEMENT = 'aisle seat' THEN 1 ELSE 0 END) AS TOTAL_AISLE_SEAT,
			COUNT(*) AS TOTAL_SEAT
		FROM SEATING_ARRANGEMENT_VIEW
		GROUP BY AIRCRAFT_CODE),
	SEAT_OCCUPANCY_SUMMARY AS
	(SELECT FSS.FLIGHT_ID,
			FSS.AIRCRAFT_CODE,
	 		ROUND((FSS.NUMBER_OCCUPIED_SEAT::numeric / NULLIF(SS.TOTAL_SEAT, 0)::numeric) * 100, 2) AS OCCUPIED_SEAT_PERCENTAGE,
	 		ROUND((FSS.NUMBER_OCCUPIED_WINDOW_SEAT::numeric / NULLIF(SS.TOTAL_WINDOW_SEAT, 0)::numeric) * 100, 2) AS OCCUPIED_WINDOW_SEAT_PERCENTAGE,
			ROUND((FSS.NUMBER_OCCUPIED_MIDDLE_SEAT::numeric / NULLIF(SS.TOTAL_MIDDLE_SEAT, 0)::numeric) * 100, 2) AS OCCUPIED_MIDDLE_SEAT_PERCENTAGE,
	 		ROUND((FSS.NUMBER_OCCUPIED_AISLE_SEAT::numeric / NULLIF(SS.TOTAL_AISLE_SEAT, 0)::numeric) * 100, 2) AS OCCUPIED_AISLE_SEAT_PERCENTAGE
	FROM FLIGHT_SEATING_SUMMARY FSS
	JOIN SEAT_SUMMARY SS ON FSS.AIRCRAFT_CODE = SS.AIRCRAFT_CODE)
SELECT * FROM SEAT_OCCUPANCY_SUMMARY;
