/*
CASE 5: Generate a view with details of each flight.
Goal: Bring seat occupancy and all details of each flight to make statistical analysis.
*/

CREATE VIEW FLIGHT_DETAIL_VIEW AS
SELECT F.FLIGHT_ID,
	AD.AIRCRAFT_MODEL,
	F.SCHEDULED_DEPARTURE,
	F.SCHEDULED_ARRIVAL,
	TO_CHAR(F.SCHEDULED_DEPARTURE, 'Day') AS FLIGHT_DAY,
	AID.DEPARTURE_CITY,
	AID.DEPARTURE_AIRPORT_NAME,
	AID.DEPARTURE_AIRPORT_COORDINATES,
	AID_2.ARRIVAL_CITY,
	AID_2.ARRIVAL_AIRPORT_NAME,
	AID_2.ARRIVAL_AIRPORT_COORDINATES,
	FSO.SEAT_OCCUPANCY,
	FSO.SEAT_NUM,
	TO_CHAR(FSO.SEAT_OCCUPANCY::double precision / FSO.SEAT_NUM::double precision * 100::double precision,
			'FM999999999.00'::text) AS RATE_OF_SEAT_PERCENTAGE,
	F.ACTUAL_DEPARTURE - F.SCHEDULED_DEPARTURE AS DELAYED_DEPARTURE,
	F.SCHEDULED_ARRIVAL - F.SCHEDULED_DEPARTURE AS FLIGHT_DURATION
FROM FLIGHTS F
JOIN
	(SELECT TF.FLIGHT_ID,
			COUNT(*) AS SEAT_OCCUPANCY,
			AC.SEAT_NUM
		FROM TICKET_FLIGHTS TF
		JOIN FLIGHTS F ON TF.FLIGHT_ID = F.FLIGHT_ID
		JOIN
			(SELECT AIRCRAFT_CODE,
					COUNT(*) AS SEAT_NUM
				FROM SEATS
				GROUP BY AIRCRAFT_CODE) AC ON F.AIRCRAFT_CODE = AC.AIRCRAFT_CODE
		GROUP BY TF.FLIGHT_ID,
			AC.SEAT_NUM) FSO ON F.FLIGHT_ID = FSO.FLIGHT_ID
JOIN
	(SELECT AIRCRAFT_CODE,
			MODEL ->> 'en'::text AS AIRCRAFT_MODEL
		FROM AIRCRAFTS_DATA) AD ON F.AIRCRAFT_CODE = AD.AIRCRAFT_CODE
JOIN
	(SELECT AIRPORT_CODE,
			AIRPORT_NAME ->> 'en'::text AS DEPARTURE_AIRPORT_NAME,
			CITY ->> 'en'::text AS DEPARTURE_CITY,
			COORDINATES AS DEPARTURE_AIRPORT_COORDINATES
		FROM AIRPORTS_DATA) AID ON F.DEPARTURE_AIRPORT = AID.AIRPORT_CODE
JOIN
	(SELECT AIRPORT_CODE,
			AIRPORT_NAME ->> 'en'::text AS ARRIVAL_AIRPORT_NAME,
			CITY ->> 'en'::text AS ARRIVAL_CITY,
			COORDINATES AS ARRIVAL_AIRPORT_COORDINATES
		FROM AIRPORTS_DATA) AID_2 ON F.ARRIVAL_AIRPORT = AID_2.AIRPORT_CODE
WHERE F.ACTUAL_DEPARTURE IS NOT NULL;