/*
CASE 1: Flight Delay Analysis
Identify the airports with the lowest average delay for flights.
*/

WITH DELAYS AS
	(SELECT F.DEPARTURE_AIRPORT,
			AD.AIRPORT_NAME ->> 'en' AS AIRPORT_NAME_IN_ENGLISH,
			AVG(F.ACTUAL_DEPARTURE - F.SCHEDULED_DEPARTURE) AS AVG_DELAY_TIME
		FROM AIRPORTS_DATA AD
		JOIN FLIGHTS F ON AD.AIRPORT_CODE = F.DEPARTURE_AIRPORT
		GROUP BY F.DEPARTURE_AIRPORT,
			AD.AIRPORT_NAME)
SELECT *
FROM DELAYS
ORDER BY AVG_DELAY_TIME